**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [23]:
import numpy as np
array = np.array([5, 15, 25, 35, 45])
array

array([ 5, 15, 25, 35, 45])

In [5]:
arr_zeros = np.zeros(7)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [8]:
arr_ones = np.ones(6)
arr_ones

array([1., 1., 1., 1., 1., 1.])

In [11]:
new_arr = np.arange(10, 20, 1)
new_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [22]:
arr1 = np.array([12, 24, 36, 48, 60])

multiplied = arr1 * 2
added = arr1 + 10
squared = arr1 ** 2
sqrt_arr = np.sqrt(arr1)

print("Оригінал: ", arr1)
print("Помножено на 2: ", multiplied)
print("Додано 10: ", added)
print("Піднесено до квадрату: ", squared)
print("Знайдено корінь: ", sqrt_arr)

Оригінал:  [12 24 36 48 60]
Помножено на 2:  [ 24  48  72  96 120]
Додано 10:  [22 34 46 58 70]
Піднесено до квадрату:  [ 144  576 1296 2304 3600]
Знайдено корінь:  [3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [20]:
data = np.array([18, 27, 33, 41, 52, 68, 79])

display(data.mean()) 
display(data.min())
display(data.max())             
display(data.sum()) 

np.float64(45.42857142857143)

np.int64(18)

np.int64(79)

np.int64(318)


---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [ ]:
arr = np.array([15, 22, 35, 44, 58, 67])

In [27]:
arr[0]

np.int64(15)

In [28]:
arr[-1]

np.int64(67)

In [30]:
arr[1:4]

array([22, 35, 44])

In [31]:
mask = arr > 40
arr[mask]

array([44, 58, 67])


---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [32]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [41]:
print(matrix.shape)
print(matrix[0])
print(matrix[:, 1])
print(matrix.sum())
print(matrix.mean())

(3, 3)
[2 4 6]
[ 4 10 16]
90
10.0
